id: PBB19D161
initial_creation_type: ocr
source_metadata:
  volumes:
    ca230060d389491f8469838f5297769e:
      base_file: v083.txt
      image_group_id: I1PD95928
      title: ཚིགས་སུ་བཅད་པའི་དོན་བསྡུས་པ་ཞེས་བྱ་བའི་བསྟན་བཅོས།
      total_pages: 1296
      volume_number: 83
